//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlParser.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public int group_id { get; set; }
        public string group_type { get; set; }
        public string group_name { get; set; }
        public string group_dname { get; set; }
        public string group_master { get; set; }
        public string group_desc { get; set; }
        public string group_photo { get; set; }
    }
}
