//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlParser.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PttBigdataEntities : DbContext
    {
        public PttBigdataEntities()
            : base("name=PttBigdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<@class> @class { get; set; }
        public DbSet<group> group { get; set; }
        public DbSet<muti_code> muti_code { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<board> board { get; set; }
        public DbSet<theme> theme { get; set; }
        public DbSet<push> push { get; set; }
    }
}
